import codeAnalyzer.CodeAnalyzer;

import java.io.FileNotFoundException;
import java.io.IOException;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) throws IOException {
        String path = args[0];
        int fileCount = new CodeAnalyzer().analyze(path).getFileCount();
        System.out.println("there are "+ fileCount + " files under path "+ path);
    }
}
