import codeAnalyzer.CodeAnalyzer;

import java.io.IOException;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) throws IOException {
        String path = args[0];
        CodeAnalyzer codeAnalyzer = new CodeAnalyzer();
        int fileCount = codeAnalyzer.anlyze(path);
        System.out.println("there are " + fileCount + " files under "+ path);
        System.out.println("total file count is " + codeAnalyzer.totalLine(path));
    }
}
