import codeAnalyzer.CodeAnalyzer;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        String path = args[0];
        int fileCount = new CodeAnalyzer().anlyze(path);
        System.out.println("there are " + fileCount + " files under "+ path);
    }
}
